const mongoose = require("mongoose");
const {ObjectId} = mongoose.Schema;

const bookingSchema = mongoose.Schema({
    booking_id:{
        type: mongoose.Types.ObjectId,
        default: mongoose.Types.ObjectId,
        unique: true
    },
    hotel_r_code:{
        type:String,
        default:""
    },
    employee_id:{
        type:String,
        default:""
    },
    departure_date:{
        type:String,
        default:""
    },
    arrival_date:{
        type:String,
        default:""
    },
    checkin_time:{
        type:String,
        default:""
    },
    checkout_time:{
        type:String,
        default:""
    },
    roomTypes: [
        {
            room_type:{
                type:String,
                default:""
            },
            rate_plan:{
                type:String,
                default:""
            },
            rate_type:{
                type:String,
                default:""
            },
            rate_plan_id:{
                type:String,
                default:""
            },
            room_type_id:{
                type:String,
                default:""
            },
            rate_type_id:{
                type:String,
                default:""
            },
            base_rate:{
                type:String,
                default:""
            },
            extra_adult_rate:{
                type:String,
                default:""
            },
            extra_child_rate:{
                type:String,
                default:""
            },
            adult_number:{
                type:String,
                default:""
            },
            child_number:{
                type:String,
                default:""
            },
            child_age:{
                type:String,
                default:""
            }
        }
    ],
    guest_title:{
        type:String,
        default:""
    },
    guest_first_name:{
        type:String,
        default:""
    },
    guest_last_name:{
        type:String,
        default:""
    },
    guest_gender:{
        type:String,
        default:""
    },
    guest_mobile_number:{
        type:String,
        default:""
    },
    guest_email:{
        type:String,
        default:""
    },
    guest_special_request:{
        type:String,
        default:""
    },
    guest_address:{
        type:String,
        default:""
    },
    guest_city:{
        type:String,
        default:""
    },
    guest_state:{
        type:String,
        default:""
    },
    guest_country:{
        type:String,
        default:""
    },
    guest_zip_code:{
        type:String,
        default:""
    },
    guest_fax:{
        type:String,
        default:""
    },
    guest_device:{
        type:String,
        default:""
    },
    discount:{
        type:String,
        default:""
    },
    payment_mode:{
        type:String,
        default:""
    },
    billing_instructions:{
        type:String,
        default:""
    },
    payment_id:{
        type:String,
        default:""
    },
    business_source:{
        type:String,
        default:""
    },
    market_segment:{
        type:String,
        default:""
    },
    company_name:{
        type:String,
        default:""
    },
    company_address:{
        type:String,
        default:""
    },
    gst_number:{
        type:String,
        default:""
    },
    special_request:{
        type:String,
        default:""
    },
    reservation_type:{
        type:String,
        default:""
    },
    booking_status:{
        type: String,
        enum:["PendingBooking", "FailBooking", "ConfirmBooking"],
        default: "FailBooking"
    },
    made_by:{
        type: String,
        recquired: true
    },
    booking_source: {
        type:String,
        default:""
    },
    business_source: {
        type:String,
        default:""
    },
    reservation_type:{
        type:String,
        default:""
    },
    total_price: {
        type:String,
        default:""
    },
    room_nights:{
        type:String,
        default:""
    },
}, {timestamps:true})

module.exports = mongoose.model('Booking', bookingSchema);
