const mongoose = require("mongoose");
const {ObjectId} = mongoose.Schema;

const bookingSchema = mongoose.Schema({
    booking_id:{
        type: mongoose.Types.ObjectId,
        default: mongoose.Types.ObjectId,
        unique: true
    },
    hotel_r_code:{
        type:String,
        default:null
    },
    employee_id:{
        type:String,
        default:null
    },
    departure_date:{
        type:String,
        default:null
    },
    arrival_date:{
        type:String,
        default:null
    },
    checkin_time:{
        type:String,
        default:null
    },
    checkout_time:{
        type:String,
        default:null
    },
    room_type:{
        type:String,
        default:null
    },
    rate_plan:{
        type:String,
        default:null
    },
    rate_type:{
        type:String,
        default:null
    },
    rate_plan_id:{
        type:String,
        default:null
    },
    room_type_id:{
        type:String,
        default:null
    },
    rate_type_id:{
        type:String,
        default:null
    },
    base_rate:{
        type:String,
        default:null
    },
    extra_adult_rate:{
        type:String,
        default:null
    },
    extra_child_rate:{
        type:String,
        default:null
    },
    adult_number:{
        type:String,
        default:null
    },
    child_number:{
        type:String,
        default:null
    },
    child_age:{
        type:String,
        default:null
    },
    guest_title:{
        type:String,
        default:null
    },
    guest_first_name:{
        type:String,
        default:null
    },
    guest_last_name:{
        type:String,
        default:null
    },
    guest_gender:{
        type:String,
        default:null
    },
    guest_mobile_number:{
        type:String,
        default:null
    },
    guest_email:{
        type:String,
        default:null
    },
    guest_special_request:{
        type:String,
        default:null
    },
    guest_address:{
        type:String,
        default:null
    },
    guest_city:{
        type:String,
        default:null
    },
    guest_state:{
        type:String,
        default:null
    },
    guest_country:{
        type:String,
        default:null
    },
    guest_zip_code:{
        type:String,
        default:null
    },
    guest_fax:{
        type:String,
        default:null
    },
    guest_device:{
        type:String,
        default:null
    },
    discount:{
        type:String,
        default:null
    },
    payment_mode:{
        type:String,
        default:null
    },
    billing_instructions:{
        type:String,
        default:null
    },
    payment_id:{
        type:String,
        default:null
    },
    business_source:{
        type:String,
        default:null
    },
    market_segment:{
        type:String,
        default:null
    },
    company_name:{
        type:String,
        default:null
    },
    company_address:{
        type:String,
        default:null
    },
    gst_number:{
        type:String,
        default:null
    },
    special_request:{
        type:String,
        default:null
    },
    reservation_type:{
        type:String,
        default:null
    },
    pickup_date:{
        type:String,
        default:null
    },
    drop_date:{
        type:String,
        default:null
    },
    booking_status:{
        type: String,
        enum:["PendingBooking", "FailBooking", "ConfirmBooking"],
        default: "FailBooking"
    },
    made_by:{
        type: String,
        recquired: true
    }
}, {timestamps:true})

module.exports = mongoose.model('Booking', bookingSchema);
